site_name: Win11 on RPI5 with QEMU
nav:
  - Home: index.md
  - User Guide: userguide.md
  - About: about.md
  - F.A.Q.: faq.md
  - Donate: donate.md
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
extra_css:
  - css/copytoclipboard.min.css
extra_javascript:
  - js/copytoclipboard.min.js